config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }

  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end    
  resources :users do
    resource :profile
  end

  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/pages/about.html.erb
<h2>About Us</h2>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to MSIN7008 Matchup</h1>
  <h3>A community site where UCL students can meet and form a team.</h3>
</div>
<div class="row">
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Your Profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
        <% else %>
          <p class="text-center">Create your profile to share your information with the community.</p>
          <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">The Community</h2>
        <p class="text-center">Visit the community to meet other marketers, developers and designers.</p>
		<%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    <div class="col-md-12">
      <div class="well">
        <h2 class="text-center">Basic Membership</h2>
        <h4 class="text-center">Sign up for free and get basic access to the community.</h4>
        <br/>
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: ' navbar-btn btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
<!--     <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
        <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div> -->
  <% end %>
</div>